language: node_js
node_js:
- '0.12'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- grunt build
addons:
  sauce_connect: true
env:
  global:
  - secure: LCqD9WcMWjqMOc2ORY/nfyVKM9GAAGdfVIRl83Ym9bFVT7odWCE+fDdPejCMXeuwhneOmEXn2BQIjhCVZYyo/38bdDVNXVeMshbpNfNCuWupbW5i3iKSCjouuclQl51GfTQo9grXonSW+uk4owkZqAQMVXlP0aOLE4iLiCpbOvzMd1o32ib2WzmWkLVjn5KGLR2kHu7KXALcqHPoDRDVXXl+ZQ+klJiXB939HJEx40a0r4AbnvLYp0sPII2G3VcgncUKnHAHaBgTCWLHaGwP3X8v8Tqxj3xJ/u64DWkhb5F/z+Xvndvlto9bL9EsUiNlIuaf7wzaQd6JvjOh28twT1A2wexhbx9Cr5AmyQeHvdKpgt2inwoeSyikOAZgtlUZFkHFpOHEr41jKXAOFW4i2D672nOkRt5hiZAtYsWdIMXBiwuvsjB0bKgJH53J5cjTyAaVqKgxFTnLprd9QIQYJUE7jWZp0Dfg+cZsWREJfskEqMiCn6gAlq6cuGqsDT5k27ZJ+QjWrbX4xTuckJOi5qpEc2gFd8GROn2coMZ+4TcPPEQBEOqLqr+EvsQ05Y0SEMiMknHnQpeJVbmzduhtB02yBFJk1E80dOBsoHN086CvIX3CH5MbR3mgDl/cbMtYouXxbvnStGVh9ABMhkhH5DHs7w6qSjybSGSoYCViXa0=
  - secure: Gs5/+/qk8WANrmF7TN1ZBLJmvJC1fUkH8B5hQAw7FFqJc0wPgjGzlpuV3xmySfGPxrt9L7GmgmgKwGChyRZzBhNLEiXbERrUL+2uVo3FY1N92AKlQmNkpD6JORdF+ZKIMuwwgdR9Vbfq2miDjfyCLweXhymx7PWMpZ0+UBIzdBf/qJbJNAiXI1cgIm2f7SsRw8U5FLEgsmGQBT5bRsL/r/4UZDyI/qm6ndEg0KoHdadbAJR0Fg7+u+3eEylRH5W5oEFSkRWoKfnHnagdkQF7s+okmMVwKJ7WFNtDH8VLsGy4iyedE/YlSjy8TiUSSJTZG90VU6ZXGcYxbpaebfwTOpHCWu7S14Lv7tx6TRayXOBgJMV48ky4zfktCPrBLmhzD2YZfgPht5UC3pQCtlOd7/uoT52fTLQZSjjBU8HgeFTgRz2FbloJGHDqpC+VdXNjoCm9UgFCoqdEC9+2ANN3CBpKqZevfKiDqrwBt8HlLsPjqnblEgmg/YD7N87Oo5F9g7RMORD1DiMvotx2LTH20cgUA1fvPEEYi7A/HXH4ZbrL6KaGzLi2uZECubrj4O2E5Mx+fIw312GcJ/53dKnPF3v26bQK3oKvRCWiS4k7J/1TliEGorLovnkD/NJl/fUi/DnccqvGmRApSyr/dN6klkgwOP1YNXIHRIO8/UMaWk4=
